### ISSUE TITLE
Realm Missing

### ISSUE THREAD

**Issue by AghaSaad04** [apiman/apiman-developer-portal#22]
Hi I am trying to setup APIMan developer portal. I have built the docker image and tried running that image
I am getting the following error in my console.
![image](https://user-images.githubusercontent.com/36513474/120325434-12a32f00-c301-11eb-903e-5e1c69b8adb3.png)

Any leads will be helpful.

**Comment by AghaSaad04** [comment]
@msavy Can you help me on this? Thanks

**Comment by volkflo** [comment]
Hi @AghaSaad04.

- Can you explain to us what steps you already tried?
- What version of apiman are you using? (quickstart will not work)
- Did you changed something about your keycloak settings?

**Comment by AghaSaad04** [comment]
So I just cloned the repository using `git clone https://github.com/apiman/apiman-developer-portal.git`
and tried building docker image by running `docker build ./` command in *Dockerfile* folder.
Then I ran `docker run -p 8080:80 <image id>`

After this I opened up the browser and getting this output in console

**Comment by volkflo** [comment]
Please use the `docker-compose.yml` to start the developer portal. (See Readme)
The docker-compose will set some variables that are required for the developer portal to run.

You need an apiman setup with keycloak and elasticsearch as data storage for the Manager UI.
Other storages for the Manager UI are not available at the moment.

**Comment by AghaSaad04** [comment]
@volkflo I did try that method as well. Let me show you the configurations and output:
### docker-compose.yml
![image](https://user-images.githubusercontent.com/36513474/120472576-7c820e00-c3bf-11eb-8aa4-e317689dbefc.png)


When I tries to access VM-IP:8445 it redirects to `http://localhost:8443/auth/realms/apiman/protocol/openid-connect/auth?client_id=devportal&redirect_uri=http%3A%2F%2Fapiman.ddns.net%3A8445%2F&state=619bf51f-403e-4ec0-a7d4-7ebabf09cf37&response_mode=fragment&response_type=code&scope=openid&nonce=713bd405-70fc-479f-b487-db7eb244dc90`

and doesn't show any UI

**Comment by volkflo** [comment]
Did you change the redirect URL in keycloak on the client `devportal` to match `http` and the changed port?
![image](https://user-images.githubusercontent.com/13332383/120490508-bdc2ef80-c3b8-11eb-9975-123d111fe1ce.png)

Also, check the environment variables again, I think your keycloak/apiman is not running http on port 8443?

**Comment by AghaSaad04** [comment]
I am unable to get any KeyCloak UI yet, so I cannot change anything from UI. So far I have only made changes in docker-compose.yml file and enabled http configs.

**Comment by volkflo** [comment]
Did you already start/configured your setup of apiman?

The Apiman Developer Portal is an application that requires a running apiman setup with a separate running keycloak setup. It is not able to run standalone without apiman.

**Comment by AghaSaad04** [comment]
Ohh I thought it's a standalone application.

I did configure apiman setup earlier but it was not in running state. Now I run both the APIMan with wildfly and apiman-devportal. I am able to access KeyCloak at VM-IP/auth

I have created the client with the `clientid : devportal` in apiman realm and set redirect url as `http:locahost:8445/*` and tried to access devportal by VM-IP:8445 but it is still redirecting to `http://localhost:8443/auth/realms/apiman/protocol/openid-connect/auth?client_id=devportal&redirect_uri=http%3A%2F%2Fapiman.ddns.net%3A8445%2F&state=d1457e0e-3d66-4144-831e-ae2446c83ff0&response_mode=fragment&response_type=code&scope=openid&nonce=36a7479a-b859-4e85-81da-3b460a6db946`

**Comment by AghaSaad04** [comment]
I am a bit confuse regarding configs. In the following attachment should red box ports be same?

![image](https://user-images.githubusercontent.com/36513474/120499949-e90a0680-c3d9-11eb-8392-291206d0a2be.png)

**Comment by AghaSaad04** [comment]
I have made changes in docker-config file and now it redirects to KeyCloak and ask for login credentials. After submitting the form, I am getting this CORS policy error. 

![image](https://user-images.githubusercontent.com/36513474/120516764-24600180-c3e9-11eb-9eaf-5aa9e2ee75ec.png)

**Comment by AghaSaad04** [comment]
@volkflo 

### Update:

CORS issue has been resolved. Now I am getting authorization issue once logged in.

![image](https://user-images.githubusercontent.com/36513474/120533603-56c62a80-c3fa-11eb-9e83-97911871fde8.png)

**Comment by volkflo** [comment]
Cool, you made some good progress.
The auth problem is related to a configuration mismatch we did not fixed yet.

There are three groups within keycloak:
![image](https://user-images.githubusercontent.com/13332383/120592402-1a1c2280-c43e-11eb-8ef4-889f3d7b2687.png)
They are renamed to
*API-Management-Administrators
*API-Management-Developer-Portal-Users
*API-Management-Users

Your user must be then in the `API-Management-Administrators` group to administrate the Developer Portal or in the `API-Management-Developer-Portal-Users` group to view only the user's data.

You can have a look into our default/example realm for keycloak here:
https://github.com/apiman/apiman/blob/85d0e2cf67a49b7a590ab745e05678e96d3c0a1d/distro/data/src/main/resources/data/apiman-realm-for-keycloak.json#L421-L464

**Comment by AghaSaad04** [comment]
@volkflo thanks for sharing the default configs. 

But I dont have any groups in my KeyCloak, I just created two of them. I have added users in these groups.

![image](https://user-images.githubusercontent.com/36513474/120642470-58413280-c48e-11eb-8f14-0bfafcc27c89.png)

Below are the available roles, I am unable to find one for the devportaluser. I have added four of them but still getting not authorized

### API-Management-Administrators:
![image](https://user-images.githubusercontent.com/36513474/120642425-495a8000-c48e-11eb-855e-ec71c92e4bbc.png)

### API-Management-Developer-Portal-Users:
![image](https://user-images.githubusercontent.com/36513474/120642727-afdf9e00-c48e-11eb-97bf-5fe8b77e794f.png)

**Comment by AghaSaad04** [comment]
Update: 
Resolved the error by creating a new realm role and adding that for user/group.

Now I cannot see any apis here. But I have created in APIMan, logged in as an admin.
### APIMan:
![image](https://user-images.githubusercontent.com/36513474/120644720-1665bb80-c491-11eb-825b-8ca170581ede.png)

### Developer Portal:
![image](https://user-images.githubusercontent.com/36513474/120644460-c850b800-c490-11eb-9b41-71a4e3a72349.png)

**Comment by volkflo** [comment]
Cool @AghaSaad04. I fixed the bug with the broken realm this morning in the upstream. You can use the apiman file from `distro/data/src/main/resources/data/apiman-realm-for-keycloak.json` to create a preconfigured realm.

Regarding the problem of not seeing an API could have multiple reasons:

- the backend of apiman currently must be elasticsearch it will not work with SQL DB (we working on that)
- only public APIs are shown automatically
- private APIs must be mapped to a user

You can have further documentation here:
https://doc.scheer-pas.com/display/APIMGMNT/Developer+Portal

**Comment by AghaSaad04** [comment]
Thanks @volkflo I will go through the docs you have shared. Moreover, API is publicly available.
Console is giving CORS error in API tab.

![image](https://user-images.githubusercontent.com/36513474/120648349-f637fb80-c494-11eb-9d92-42541bc25197.png)

**Comment by volkflo** [comment]
Which version of apiman are you using? 
Apiman 2.0.0.Final was released before the Developer Portal was included.
At the moment you have to build apiman on your own (the next apiman release coming in a few weeks).

**Comment by AghaSaad04** [comment]
Yes I am using Apiman 2.0.0.Final.

**Comment by volkflo** [comment]
You can try to build the current master branch of apiman our you could wait till we release the next version of apiman.Let us know if you need further help :)Am 03.06.21, 15:44 schrieb Agha Saad Fraz ***@***.***>:

   
  Yes I am using Apiman 2.0.0.Final.

**Comment by AghaSaad04** [comment]
For now I will try building the master branch and will use the new release afterwards. I am closing this issue for now. will reopen or create a new one if I further need help. Thanks a lot for the quick and detailed responses.
